Teleport:
  # 检测延迟时间
  delay: 3
data:
  # mysql, sqlite
  storage-type: sqlite
  # mysql 才有效
  address: localhost
  port: 3306
  database: ari
  username: root
  password: 123456
  maximum-pool-size: 10
  minimum-idle: 10
  maximum-lifetime: 1800000
  connection-timeout: 5000
  keepalive-time: 0
debug:
  enable: true
  overwrite-file: true
experimental:
