name: ari
version: '${project.version}'
main: com.tty.Ari
api-version: '1.21'
authors:
  - Arilo007
folia-supported: true
dependencies:
  server:
    arilib:
      required: true
      load: BEFORE
    PlaceholderAPI:
      required: false
    WorldGuard:
      required: false
