name: ari
version: '${project.version}'
main: com.tty.Ari
api-version: '1.21'
authors:
  - Arilo007
folia-supported: true
loader: com.tty.Loader
has-open-classloader: true
dependencies:
  server:
    arilib:
      required: true
    PlaceholderAPI:
      required: false
    WorldGuard:
      required: false
