name: ari
version: '${project.version}'
main: com.tty.Ari
api-version: '1.21'
authors:
  - Arilo007
folia-supported: true
dependencies:
  server:
    arilib:
      load: 'BEFORE'
      required: true
    Vault:
      required: true
    PlaceholderAPI:
      required: false
