name: Ari
version: '${project.version}'
author: Arilo007
folia-supported: true
main: ari.superarilo.Ari
#depend: ['']
#softdepend: ['']
api-version: 1.20
commands:
  arilo:
    aliases:
      - 'ari'
    usage: '插件主要指令'
  tpa:
    usage: '传送指令'
  tpaaccept:
    usage: '传送接受指令'
  tpahere:
    usage: '传送指令'
  tparefuse:
    usage: '拒绝传送指令'